### PR TITLE
Add Laurynas' MySQL development tools

### PR DESCRIPTION
**Pull request by laurynas-biveinis**

### CODE REVIEW

**Review by federico-razzoli — CHANGES_REQUESTED** [review]
Hey @laurynas-biveinis ! Can you specify if your collection is known to work with MariaDB, and if it's known to have major problems?
Having problems or being not tested with Maria won't prevent acceptance. But it's something that Maria users will want to know.
I will also make some changes to the page, but don't worry about it. And feel free to add any other article / script you consider useful.

**Comment by laurynas-biveinis** [comment]
> Hey @laurynas-biveinis ! Can you specify if your collection is known to work with MariaDB, and if it's known to have major problems? Having problems or being not tested with Maria won't prevent acceptance. But it's something that Maria users will want to know.

I never tested it with MariaDB, but the tools mostly are agnostic WRT source code specifics, so I expect the same level of compatibility and would treat any bugs equally as for MySQL.

**Comment by federico-razzoli** [comment]
@laurynas-biveinis I suggest you add a note like "Not tested with MariaDB, but it's expected to work equally well".

**Comment by laurynas-biveinis** [comment]
@federico-razzoli added, how does it look?

**Review by federico-razzoli — APPROVED** [review]

**Pull request merged**
